#jekyll serve

# Site wide configuration

title: 攻城狮朋友圈：终日乾乾，或跃在渊
description: 不等不靠，有囧有料，攻城狮建造世界
logo: logo/120x120-moilion.png
teaser: logo/400x250-skill.png
#url: http://127.0.0.1:4000
#url: http://192.168.1.122:4000
url: http://www.moilioncircle.com

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title.html
#markdown: redcarpet
#highlighter: pygments
markdown: kramdown
highlighter: rouge

kramdown:
  input:          GFM
  hard_wrap:      false

gems:
  - jekyll-sitemap

redcarpet:
  extensions: ["fenced_code_blocks","tables","autolink","strikethrough","no_intra_emphasis"]

# Site owner
owner:
  name: "史荣久"
  web: http://www.trydofor.com
  bio: "$implicity is everything, since valentine's day 2004."
  avatar: user/shi.rongjiu.jpg


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
